add axi4-lite default target
xlsynth/bedrock-rtl pull request #233
Opened 2024-12-04 18:36 UTC by tbunker-openai

2024-12-06 17:52 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_split.sv
> +// TODO: This does not support ID tracking, so we assume that the same ID
i dont think axi-lite supports multiple IDs anyway?

2024-12-06 17:54 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
how do you deal with the fact that the responses might come back out of order? Don't you need to limit the number of outstanding to 1 (or only allow 1 branch to have transactions outstanding at a time)? I didn't see that anywhere.

2024-12-06 18:05 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +// TODO: This does not support ID tracking, so we assume that the same ID
You're right! That makes it easier. I'll remove this note.

2024-12-06 18:06 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
Your question above made me double-check the AXI4-Lite specification which says that there can only be one outstanding transaction. So, this is handled already.

2024-12-06 18:11 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
No I don't believe that is correct.

Lite has only one stream ID. And all transactions are limited to 1 beat. But there can still be multiple transactions in flight. And because there is only one stream, the responses must come back in the same order that the requests were issued.

2024-12-06 18:30 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
Ah, okay. Without IDs, I think the only way to handle this is to track if there are *any* outstanding transactions and if a new request wants to take a different route, block it until the outstanding transactions have completed. Let me update that.

2024-12-06 18:35 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
sounds right. and even with IDs you would still need to do it (if two txns have same ID but want to go different ways).

2024-12-06 20:41 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
Added support

2024-12-07 00:02 UTC, bgelb-openai requested changes

2024-12-07 00:02 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_default_target.sv
> +  always_ff @(posedge clk) begin
This RTL feels very "bare metal" to me. I think there should be a way to write it that is more correct by construction and leave a lot fewer places for bugs to hide.

My comment applies to the splitter as well, but for now I am focusing on the responder because it is smaller.

Key primitive I would use is a "token FIFO". That is basically a FIFO that has an empty data bus (its just passing a "token" representing a valid element, even though we don't need any data to go along with it since we don't care about the payload of the AW or W). Could probably just use a standard bedrock flops FIFO with a width of 1 (and drive a constant into it, which should let the data flops get optimized away). Can set depth to 1 as well as we don't care about throughput.

Taking AW+W -> B as the example, I would do the following:
- instance a token FIFO for AW and a second one for W. The push side just hooks directly to the AW and W interface ports.
- logic is then as follows:

assign bresp_valid = awfifo_pop_valid && wfifo_pop_valid;
assign awfifo_pop_ready = bresp_ready && bresp_valid;
assign wfifo_pop_ready = bresp_ready && bresp_valid;
(plus constant assign for response code)

Thats it! And those three lines are the only code that is not coming from a library. Easy to evaluate by inspection.

2024-12-07 00:12 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_default_target.sv
> +  assign target_rdata = '0;  // ri lint_check_waive CONST_ASSIGN CONST_OUTPUT
I'll create a parameter.

2024-12-07 00:18 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_default_target.sv
> +  always_ff @(posedge clk) begin
I will make the changes, and I understand your point about using library components as much as possible. My two cents: I'm not fully convinced that using things like `BR_REG` or other bedrock components is actually more correct and leads to fewer bugs. In my opinion, you can potentially make the same bugs when instantiating and connecting bedrock components together. In this case, I do agree that because this module is simple, using bedrock components as the right approach.

2024-12-07 00:41 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_default_target.sv
> +  always_ff @(posedge clk) begin
Team has aligned on BR_REG usage. So I think that should be the norm unless we can clearly articulate the reasons why its not appropriate for a given case. We probably need to document this better, which I think is a fair complaint :).

I agree in more complex cases it is not always as clear cut when to use a lib component vs roll something new (and whether or not to attempt to put the new thing in the library), and we should be careful about obsessing over it.

Please do note though that my feedback here is not just on using / not using the library (which can definitely tend to the philosophical). It is also about how to make the code as clear and easy to reason about as possible.

2024-12-07 01:22 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_default_target.sv
> +  always_ff @(posedge clk) begin
Agreed. I've updated both this module and the axi_split module.

2024-12-07 01:22 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +  // Counters to track outstanding read transactions
Done. I also updated the registers to use the macros.

2024-12-07 03:50 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_split.sv
> +  `BR_REGLN(last_arvalid_is_branch, branch_araddr_in_range, ar_handshake_valid)
if this flop is going to be non-reset i think it would be good to add an assert that it will not be X if no_outstanding_reads==0.

2024-12-07 04:15 UTC, bgelb-openai approved these changes
couple minor items for your review, but looks good! thanks trevor

2024-12-07 04:15 UTC, bgelb-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
since you prevent both branch and trunk from being active at a time, do you need this arbiter?

I think you could make it simple priority instead of rr at very least... but I think you should be able to get rid of it altogether (though I would add some asserts to check that at most _req is hot at a time)

2024-12-09 17:08 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +  `BR_REGLN(last_arvalid_is_branch, branch_araddr_in_range, ar_handshake_valid)
Done

2024-12-09 17:08 UTC, tbunker-openai commented on amba/rtl/br_amba_axil_split.sv
> +  br_arb_rr #(
Yes, you are correct. I will modify it and add the assertion.

2024-12-09 17:51 UTC, merged