amba: add axi4 to axi4-lite bridge
xlsynth/bedrock-rtl pull request #277
Opened 2024-12-20 21:35 UTC by tbunker-openai

2024-12-20 22:46 UTC, bgelb-openai commented on amba/rtl/br_amba_axi2axil.sv
> +// NOTE: This module does not support multiple outstanding AXI4 transactions. If there is a pending
If we are planning to use this at the NIC400->util noc interface, this seems like a problem. The latency is long on the util noc, and it would be nice to support multiple outstanding.

2024-12-20 23:15 UTC, tbunker-openai commented on amba/rtl/br_amba_axi2axil.sv
> +// NOTE: This module does not support multiple outstanding AXI4 transactions. If there is a pending
I agree. Maybe I should change this to "TODO" instead of "NOTE". This was just the start to make sure we split burst transactions into single-beat transactions. Supporting multiple outstanding transactions (and for separate IDs) will require more tracking.

2024-12-21 00:43 UTC, bgelb-openai commented on amba/rtl/br_amba_pkg.sv
> +    AxiBurstReserve = 2'b11   // Reserved
d

2024-12-21 00:58 UTC, bgelb-openai commented on amba/rtl/br_amba_axi2axil.sv
> +  // ri lint_check_off GRAY_CODE_FSM
I feel this implementation really won't lend itself to multiple transactions outstanding, because the FSM is watching both request and response. I am imagining a more "streaming" implementation that I think will be pretty simple and should scale much better. Discuss after break?

2024-12-30 21:09 UTC, tbunker-openai commented on amba/rtl/br_amba_axi2axil.sv
> +  // ri lint_check_off GRAY_CODE_FSM
Yes, I know what you're saying. Let me adjust the implementation to be more streaming, decoupling the responses from the requests.

2025-01-02 19:12 UTC, bgelb-openai commented on amba/rtl/br_amba_axi2axil.sv
> +  // ri lint_check_off GRAY_CODE_FSM
SGTM. I think it should be possible to share the read and write unrolling/recombining logic for the most part as well. You'd have two instances of the core portion, with optional datapaths beside it that are switched on/off for read vs write.

On the request side you can unroll. And then have a FIFO to the response side that indicates for each response received from AXI-Lite, whether to generate a response to the AXI side or not (along w/ ID and LAST values).

2025-01-03 00:26 UTC, tbunker-openai commented on amba/rtl/br_amba_axi2axil.sv
> +// NOTE: This module does not support multiple outstanding AXI4 transactions. If there is a pending
I implemented the streaming version and removed the NOTE.

2025-01-03 00:27 UTC, tbunker-openai commented on amba/rtl/br_amba_pkg.sv
> +    AxiBurstReserve = 2'b11   // Reserved
Was this comment accidental?

2025-01-03 00:27 UTC, tbunker-openai commented on amba/rtl/br_amba_axi2axil.sv
> +  // ri lint_check_off GRAY_CODE_FSM
Updated. I'm going to try to test this in chili-hw-monorepo.

2025-01-03 00:40 UTC, bgelb-openai commented on amba/rtl/br_amba_pkg.sv
> +    AxiBurstReserve = 2'b11   // Reserved
well... it was supposed to have more letters in it :)

Was suggesting last entry be "AxiBurstReserved"

2025-01-03 00:56 UTC, tbunker-openai commented on amba/rtl/br_amba_pkg.sv
> +    AxiBurstReserve = 2'b11   // Reserved
Ah, got it :-) !

2025-01-03 00:56 UTC, tbunker-openai commented on amba/rtl/br_amba_pkg.sv
> +    AxiBurstReserve = 2'b11   // Reserved
Done

2025-01-03 17:33 UTC, bgelb-openai requested changes
"streaming" design much better! please see comments

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +        axi_req_ready  = axil_req_ready && !resp_fifo_push_ready;
It seems like all this FSM does really is manage loading the staging flops.

Why not just leave the incoming request on the interface, and don't assert axi_req_ready (popping/accepting the request) until the count reaches burst_len? Then you could eliminate all the input staging flops as well as this FSM.

Then axi_req_valid stays high for all beats of the transfer. And your two cases for axil_req_valid would collapse into one. i.e. there is no special casing for "one beat" vs. "multiple beats". It would be same logic for both (just that the max value of counter would only reach 0 in the single beat case).

I feel like the counter gives all the state you really need, and the additional state here is redundant.

If you're worried about timing on axi_req interface (or don't trust the requester to keep the request stable, even though AXI requires it), can just add a flow reg on the input. That would effectively give you the staging flops but keeping them isolated from the unrolling logic.

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  assign burst_len_extended = {1'b0, req_burst_len};  // ri lint_check_waive ZERO_EXT
why is this needed? lint problems? should be OK to just do the comparison w/o extension I think and just waive the lint warningg.

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +        if (axil_req_handshake && (req_count > burst_len_extended)) begin
shouldn't this be == not >?

i.e., I think in a 4-beat burst, req_burst_len in 3. And req_count on the final beat would also be 3?

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  assign resp_fifo_push_data = {current_req_id, req_count > burst_len_extended};
can you give req_count > burst_len_extended a name? rather than burying inside the {}

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      .Width(IdWidth + 1),  // ID + is_last
use $bits(is_last) perhaps?

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  logic [(IdWidth + 1)-1:0] resp_fifo_push_data, resp_fifo_pop_data;
plz define a localparam for this type width so that the Fifo Width and variable sizes are set using the same definition.

alternatively, you could just pass the {} vector into the in and out of the FIFO and not declare this combined "data" bus explicitly. Then the FIFO width would be the only place that needs this value (so could derive it locally to the FIFO w/o a param).

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  assign resp_fifo_pop_ready = axi_resp_handshake;
i think there is a mismatch here. A write transaction will have burst_len axil_req_handshake beats, but only have 1 axi_resp_handshake beat.

Should the fifo be popped on every axil_resp_handshake instead?

I think I would try to tie the resp FIFO to just the AXIL side so that the contents in the FIFO are always 1:1 with number of axil reqs/responses.

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  `BR_REGLN(current_req_id, axi_req_id, axi_req_handshake)
why is this one named differently from all the other req_ signals?

2025-01-03 17:33 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      .Width(IdWidth + 1),  // ID + is_last
see earlier comment about localparam.

2025-01-03 17:34 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  assign resp_fifo_push_data = {current_req_id, req_count > burst_len_extended};
(you could probably use this signal in the unrolling logic as well, so that the explicit comparison is only written once).

2025-01-03 17:50 UTC, tbunker-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  // ri lint_check_off NOT_READ
Done.

2025-01-03 17:53 UTC, tbunker-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      (axi_req_burst == br_amba::AxiBurstIncr) || (axi_req_burst == br_amba::AxiBurstFixed);
I'll add it. It adds a little complexity (some more shifters) to the next_address logic, but it's not terrible. The only place I have ever seen WRAP used is for cache line refills, and I don't think AXI4-Lite would be the right interface for that :-). But I agree that we might as well add it.

2025-01-03 18:49 UTC, tbunker-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +        if (axil_req_handshake && (req_count > burst_len_extended)) begin
Yes, you are right. I didn't update this when I changed the implementation.

2025-01-03 21:29 UTC, bgelb-openai reviewed
just a few last comments for your review. please take a look

2025-01-03 21:29 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      StateIdle: begin
Is it intended that the idle state adds a bubble now? I.e. nothing comes out axil side until you reach StateReqSplit?

why can't you just have:
axil_req_valid = axi_req_valid && resp_fifo_push_ready
axi_req_ready = axil_req_handshake && is_last_req_beat

and delete the FSM entirely?

2025-01-03 21:29 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      .reinit(axi_req_handshake),
this reinit had a surprising behavior that if incr_valid is asserted the next value is init_value+incr (not init_value). My expectation would have been that reinit took priority over incr.

2025-01-03 21:29 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      .initial_value({{br_amba::AxiBurstLenWidth{1'b0}}, 1'b1}),
doesn't this need to be init to 0? not 1? (axi_req_len is defined as N-1)

2025-01-03 22:21 UTC, bgelb-openai approved these changes
looks great. Please address the last comment, then good to go!

2025-01-03 22:21 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      .initial_value({(br_amba::AxiBurstLenWidth + 1) {1'b0}}),
i don't think this needs to be width +1. Because it counts from 0 to N-1 for an N beat burst.

2025-01-03 22:21 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +  assign is_last_req_beat = (req_count[br_amba::AxiBurstLenWidth-1:0] == axi_req_len);
you never use the upper bit because its always 0 :)

2025-01-03 22:21 UTC, bgelb-openai commented on amba/rtl/internal/br_amba_axi2axil_core.sv
> +      .MaxValue(1 << br_amba::AxiBurstLenWidth),
max value is 2**LenWidth - 1, I think?

2025-01-03 22:26 UTC, merged